In [1]:
# Import necessary libraries
import pandas as pd

In [2]:
# Read relevant data
sat = pd.read_csv("./data/sat_2019_ca.csv")
act = pd.read_csv("./data/act_2019_ca.csv")
districts = pd.read_csv("./data/california_school_district_info.csv")

In [5]:
print(districts.shape)
districts.head()

(944, 69)

,OBJECTID,Year,FedID,CDCode,CDSCode,CountyName,DistrictNa,DistrictTy,GradeLow,GradeHigh,...,AbsentElig,AbsentPct,GradCohort,GradPct,UCCSUReqMe,DropOutPct,EnrollCumu,SuspPct,SHAPE_Leng,SHAPE_Area
0,1,2018-19,601770,161119,1611190000000,Alameda,Alameda Unified,Unified,KG,12,...,11453.0,9.4,882.0,88.900002,58.900002,5.2,11600.0,2.6,57196.403944,4.733304e+07
1,2,2018-19,601860,161127,1611270000000,Alameda,Albany City Unified,Unified,KG,12,...,3763.0,6.4,301.0,94.699997,63.900002,1.7,3830.0,1.9,12870.772156,7.161276e+06
2,3,2018-19,604740,161143,1611430000000,Alameda,Berkeley Unified,Unified,KG,12,...,10404.0,9.7,856.0,87.400002,83.300003,10.7,10534.0,1.4,44426.287405,4.376389e+07
3,4,2018-19,607800,161150,1611500000000,Alameda,Castro Valley Unified,Unified,KG,12,...,9433.0,7.4,742.0,92.599998,55.900002,3.0,9532.0,2.2,142338.494091,2.833205e+08
4,5,2018-19,612630,161168,1611680000000,Alameda,Emery Unified,Unified,KG,12,...,760.0,20.5,40.0,100.000000,40.000000,0.0,780.0,3.6,13762.869292,5.368212e+06

In [4]:
sat.head()

,CDS,CCode,CDCode,SCode,RType,SName,DName,CName,Enroll12,NumTSTTakr12,...,NumERWBenchmark11,PctERWBenchmark11,NumMathBenchmark11,PctMathBenchmark11,TotNumBothBenchmark12,PctBothBenchmark12,TotNumBothBenchmark11,PctBothBenchmark11,Year,Unnamed: 25
0,6.615981e+12,6.0,661598.0,630046.0,S,Colusa Alternative Home,Colusa Unified,Colusa,18.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-19,NaN
1,6.616061e+12,6.0,661606.0,634758.0,S,Maxwell Sr High,Maxwell Unified,Colusa,29.0,10.0,...,*,*,*,*,*,*,*,*,2018-19,NaN
2,1.964733e+13,19.0,1964733.0,1930924.0,S,Belmont Senior High,Los Angeles Unified,Los Angeles,206.0,102.0,...,42,24.14,12,6.90,14,13.73,11,6.32,2018-19,NaN
3,1.964733e+13,19.0,1964733.0,1931476.0,S,Canoga Park Senior High,Los Angeles Unified,Los Angeles,227.0,113.0,...,97,35.27,37,13.45,18,15.93,35,12.73,2018-19,NaN
4,1.964733e+13,19.0,1964733.0,1931856.0,S,Whitman Continuation,Los Angeles Unified,Los Angeles,18.0,14.0,...,*,*,*,*,*,*,*,*,2018-19,NaN

In [23]:
act.head()

,CDS,CCode,CDCode,SCode,RType,SName,DName,CName,Enroll12,NumTstTakr,AvgScrRead,AvgScrEng,AvgScrMath,AvgScrSci,NumGE21,PctGE21,Year,Unnamed: 17
0,3.366993e+13,33.0,3366993.0,129882.0,S,21st Century Learning Institute,Beaumont Unified,Riverside,18.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2018-19,NaN
1,1.964212e+13,19.0,1964212.0,1995596.0,S,ABC Secondary (Alternative),ABC Unified,Los Angeles,58.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2018-19,NaN
2,1.563776e+13,15.0,1563776.0,1530377.0,S,Abraham Lincoln Alternative,Southern Kern Unified,Kern,18.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2018-19,NaN
3,4.369666e+13,43.0,4369666.0,4333795.0,S,Abraham Lincoln High,San Jose Unified,Santa Clara,463.0,53.0,23,22,22,23,34,64.15,2018-19,NaN
4,1.964733e+13,19.0,1964733.0,1935121.0,S,Abraham Lincoln Senior High,Los Angeles Unified,Los Angeles,226.0,19.0,21,20,23,22,11,57.89,2018-19,NaN

In [14]:
sat["CDCode"].unique().shape

(599,)

In [15]:
districts["CDCode"].shape

(944,)

In [47]:
count = 0
count_not = 0
sat_codes = []
for i, v in enumerate(sat["CDCode"].astype(float).unique()):
    if v in districts["CDCode"].astype(float).unique() and v in act["CDCode"].unique():
        sat_codes.append(int(v))
        count +=1 
    else: 
        count_not +=1

In [48]:
count

460

In [49]:
sat_codes

[661598,
 661606,
 1964733,
 3073635,
 3367215,
 1363107,
 3367033,
 3667827,
 1563776,
 1964634,
 3367181,
 3675051,
 3675077,
 3768338,
 1062117,
 3367090,
 3968676,
 1975713,
 2966357,
 3073650,
 4168924,
 761796,
 1263040,
 1964246,
 1964873,
 3175085,
 3768163,
 4169047,
 4169070,
 161200,
 1162646,
 3467314,
 3868478,
 161259,
 2165482,
 3467421,
 4269229,
 761721,
 1075234,
 1075275,
 3375176,
 3667678,
 961853,
 1964394,
 2465755,
 3667876,
 3968585,
 1965060,
 2465789,
 3467447,
 1262810,
 2065201,
 2065243,
 3166894,
 1964568,
 1973437,
 3066670,
 3476505,
 3675044,
 3768346,
 4970722,
 4970730,
 4776455,
 5471803,
 161119,
 1563529,
 1965128,
 1965136,
 3066647,
 3667934,
 4369427,
 3976760,
 5475325,
 4870540,
 5472249,
 3768411,
 4068841,
 4369534,
 161127,
 1062414,
 5071134,
 5672546,
 5071175,
 4469823,
 1964378,
 3066514,
 3066522,
 3467439,
 3768296,
 4275010,
 4276786,
 5075739,
 1563818,
 1973445,
 1975291,
 1975309,
 161176,
 1075127,
 1875036,
 3073924,
 761788,
 1262687,
 3066431,
 3375242,
 3667710,
 1964881,
 3667843,
 3768304,
 1964865,
 2165417,
 3667777,
 1964451,
 3367082,
 3968593,
 561556,
 661614,
 2773825,
 4068809,
 2075606,
 2076414,
 3166928,
 3667736,
 3768106,
 3768130,
 4269112,
 3066548,
 3367058,
 1965094,
 2573593,
 3968627,
 4369401,
 5472256,
 3768213,
 5772702,
 5271571,
 5376513,
 461432,
 1062166,
 3367124,
 1563685,
 4970870,
 5575184,
 3768452,
 4970953,
 1964725,
 1964774,
 1975333,
 3375200,
 3773791,
 4369666,
 5672652,
 5071217,
 1964337,
 3366993,
 5171464,
 461424,
 461440,
 1964535,
 2765979,
 161242,
 1363115,
 3467330,
 761648,
 761663,
 1062547,
 1764014,
 1764022,
 3375192,
 3667686,
 3768023,
 373981,
 461408,
 1563628,
 2766092,
 1964584,
 3367207,
 561564,
 1062265,
 1964659,
 1864139,
 1976869,
 161192,
 1964352,
 2365565,
 161291,
 1965029,
 1964279,
 3667801,
 3768189,
 4169062,
 1663925,
 2866241,
 175101,
 3066621,
 4670177,
 973783,
 4068759,
 4369468,
 5475523,
 4970920,
 4369674,
 5071043,
 4168890,
 4970961,
 4975358,
 5673874,
 5073601,
 3968577,
 4570136,
 761754,
 5772678,
 761804,
 2165466,
 1964212,
 3066449,
 161309,
 2475317,
 2475366,
 2775473,
 3767983,
 3768403,
 1964857,
 3066464,
 761630,
 1663891,
 3667652,
 1964527,
 4870573,
 761697,
 861820,
 961838,
 3066597,
 4369583,
 5672603,
 3775416,
 3775614,
 5673759,
 1864162,
 1964790,
 5673940,
 1964980,
 2365623,
 4469799,
 2173361,
 5171415,
 3367173,
 1062364,
 1062380,
 3367249,
 3373676,
 3667611,
 161275,
 1964436,
 1563412,
 3166944,
 1964907,
 1663875,
 1973460,
 3575259,
 3773551,
 4369641,
 1363149,
 1964303,
 1073809,
 3768049,
 4975390,
 3366977,
 3467413,
 5171373,
 4770516,
 4773684,
 3473973,
 5471860,
 4970656,
 4970839,
 5572413,
 1964840,
 4469807,
 4570169,
 1964519,
 161234,
 3768122,
 1062125,
 1073965,
 3667850,
 4269328,
 2365540,
 761739,
 1075408,
 3773569,
 661622,
 1964683,
 2866266,
 5271506,
 4870532,
 3475283,
 3667959,
 5471993,
 461531,
 2766159,
 1573742,
 1973452,
 5071092,
 5872769,
 4569856,
 1964329,
 1563826,
 3975499,
 1062539,
 1964261,
 3768171,
 1062331,
 1663958,
 3073643,
 4369609,
 4973882,
 5672520,
 5471837,
 4970607,
 4068700,
 4369484,
 4970862,
 4475432,
 5075556,
 5772710,
 1363214,
 4269310,
 5872728,
 3673890,
 961903,
 2465730,
 1673932,
 1764030,
 1975341,
 161168,
 1764055,
 3266969,
 1563677,
 1964287,
 4269260,
 5171407,
 161143,
 1964709,
 2365599,
 1964311,
 1964964,
 1162661,
 1964592,
 1573908,
 3673957,
 4569989,
 4870565,
 4970706,
 5572389,
 1663982,
 3667868,
 3968502,
 5171456,
 5075564,
 2365615,
 2766068,
 1262901,
 1062158,
 2673692,
 1076778,
 1176562,
 2075580,
 1964808,
 4168999,
 5271639,
 4870581,
 5475531,
 5872736,
 3366985,
 1073999,
 1275515,
 1964295,
 1964469,
 4575267,
 3968650,
 3166951,
 4870524,
 461515,
 1062257,
 1563859,
 4970904,
 3968569,
 3066555,
 1776976,
 2573585,
 2673668,
 3667892,
 2365581,
 475507,
 1575168,
 3166845,
 5071068,
 1964576,
 4770466,
 5472140,
 5476836,
 5676828,
 5772686,
 4269146,
 3367157,
 1964691,
 3667637,
 4075457,
 5075572,
 5375028,
 2473619,
 4970797,
 3667587,
 5672454,
 1062430,
 5171449,
 5772694,
 1363099,
 1363164,
 1275374,
 1476687,
 2465698,
 1964444,
 175093,
 2866290,
 5476794,
 4168940,
 4373387,
 4469765,
 5171423,
 3467355,
 5171399,
 161150,
 1363081,
 2766134,
 3675069,
 3367116,
 1075598,
 4168916,
 1175481,
 3776851,
 1263032,
 1965052,
 2765987,
 1062281,
 2775440,
 3567538,
 2265532,
 1463289,
 2365607,
 1864089,
 3768031,
 4770250,
 4068833,
 4075465,
 5672470,
 4570110,
 2373866,
 2373916,
 5075549]

In [32]:
act["CDCode"].unique()

array([3366993., 1964212., 1563776., 4369666., 1964733., 1976968.,
       1964246., 3868478., 3675077., 3667736., 1965136., 1262810.,
        761630., 5472249., 4369427., 3667934., 5672546., 4369674.,
       1964683.,  161119.,  161127., 1263032., 1975713.,  761739.,
       2766159., 3066464., 5471803., 3667652., 4276786., 3675051.,
        373981.,  175101., 1062380., 2866266.,  161176.,  161259.,
       3066431., 1976885., 4970607., 4569856., 2365540., 1964568.,
       4870540., 1964634., 1964709., 4369583., 3166928., 1964857.,
        761648., 3575259., 1964808., 4469799., 4169047., 1964261.,
       1262687., 4469823., 3367215., 3073643., 4068759., 1964519.,
        161309., 3667876., 3467439., 1563529., 3467447., 3968585.,
       4168999., 3968676., 1910199.,  761796., 5071175., 1975309.,
       4068700., 2465789., 3768338., 3777032., 3768106., 1964725.,
       1673932., 1964881., 1964279., 1964287., 3366985., 3667611.,
       1964295., 3968593., 2966357., 1964303., 4870524.,  161143.,
       1964311., 3667637., 1010108., 1864089.,  461408., 1476687.,
       2910298., 3667686., 3066522., 1964329., 3768411., 3776851.,
       1563685., 3767983., 4369401., 1363081., 3066449.,  561556.,
       1062117., 5672652., 3066514., 1062166., 1964337., 4569989.,
       1573742., 4773684., 5475523., 4269229.,  561564., 1363099.,
       1563677., 1764055., 3968650., 5310538.,  761804., 1965128.,
       3367207., 3775416., 5171415.,  131617., 3331625., 1964469.,
       3667892., 4275010., 4970722., 1965094., 3768403., 3968627.,
       4970797., 1062331., 1663875., 1563628., 4168916., 1363107.,
       2866241., 3768213., 3768346., 3066621., 3367124., 4169062.,
       3773551., 2765987., 4269146., 1075598., 4970862.,  810082.,
        161150., 3367173., 3367033., 1973437., 3473973., 1964352.,
       1073965., 1363115., 5071043., 4575267., 5673759., 3066670.,
       1563412., 3375192., 3673957.,  910090., 1964378., 2075606.,
       1062125., 3266969.,  461424., 3667678., 2065201., 4369484.,
       3768023., 3667710., 3375242., 3667843., 1964394.,  961838.,
        710074., 1764030., 4970656., 3373676., 3066548., 4075465.,
       3773569., 3166944., 2673668., 3166894., 3010306., 1410140.,
        761754.,  661598.,  410041., 2410249., 3476505., 5075572.,
       5572413., 1663891., 3467330., 5872728., 3110314., 5271506.,
       3066597., 3768031., 3467314., 1964436., 4973882., 5472140.,
       1062547., 2465755.,  161234., 1964444., 4369468., 4469765.,
       5772678., 1976869.,  161242., 3768049.,  861820., 3768296.,
       2475366., 3467413., 5071068., 1973460., 1964907., 3768163.,
       3710371., 5475531., 3475283., 4870532., 5575184., 2475317.,
       1964451., 4310439.,  175093., 1062265., 4770250.,  461432.,
       5171373., 5075739.,  961853., 3667850., 3768130., 4169070.,
       3066647., 5472256., 1964527., 1964535., 3073635., 5410546.,
       4870573., 1076778., 4970920., 3375176.,  161168., 3675044.,
       4570136., 1964691.,  110017., 4269310., 3968502., 5772686.,
       4776455., 1275515., 3610363., 3310330., 5476836., 3768122.,
       4269112., 5475325., 1275374., 5672454., 1073809., 3773791.,
       2365565., 1062158., 1575168.,  761721., 2065243., 3768304.,
       1975291., 3467355., 4970706., 2076414., 1973445., 1964576.,
       4710470.,  973783., 5672470., 2775473., 1964584.,  161200.,
       2766068.,  475507., 4010405., 3777099., 3768452., 2473619.,
       4168890., 1062414., 1176562., 3367082., 1663925., 4770466.,
       5071092., 1964592.,  161192., 4975390., 4369641., 1875036.,
       3776471., 3366977., 2465698., 1363149.,  461531., 1262901.,
       3367058., 3166951., 5075549., 1363164., 1310132., 4075457.,
       5171456.,  461440., 1973452., 3073650., 5673940., 4168924.,
       4870581., 3166845., 3975499., 1964840.,  761697., 3768171.,
       3367090., 1764014., 1073999., 5071134., 1663958., 1062257.,
       1764022., 1964659., 3066555.,  461515., 1864139., 1062281.,
       2373916., 2465730., 2766092., 1663982., 2075580., 3968569.,
       3968577., 5872736., 5471993., 5171399., 1463289., 1864162.,
       3073924., 4369609., 4369534., 5271571., 4670177., 1964774.,
       3076893., 1964980., 2673692., 2265532.,  661606., 1573908.,
       2365581., 1075127., 2710272.,  161275., 4373387., 1975333.,
       2573585., 3667827., 1964790., 5672603., 4068809., 3367249.,
       3976760.,  510058., 3375200.,       0.,  161291.,  310033.,
        661614.,  661622.,  761663.,  761788.,  961903., 1062364.,
       1062430., 1062539., 1075234., 1075275., 1075408., 1110116.,
       1162646., 1162661., 1175481., 1210124., 1263040., 1363214.,
       1510157., 1563818., 1563826., 1563859., 1610165., 1776976.,
       1964865., 1964873., 1964964., 1965029., 1965052., 1965060.,
       1975341., 1975663., 1975697., 2010207., 2110215., 2165417.,
       2165466., 2165482., 2173361., 2310231., 2365599., 2365607.,
       2365615., 2365623., 2373866., 2573593., 2610264., 2765979.,
       2766134., 2773825., 2775440., 2810280., 2866290., 3175085.,
       3367116., 3367157., 3367181., 3410348., 3467421., 3567538.,
       3667587., 3667777., 3667801., 3667868., 3667959., 3673890.,
       3675069., 3768189., 3775614., 3777107., 3810389., 3910397.,
       4068833., 4068841., 4110413., 4168940., 4210421., 4269260.,
       4269328., 4277198., 4277206., 4277214., 4277222., 4410447.,
       4469807., 4475432., 4510454., 4570110., 4570169., 4770516.,
       4810488., 4870565., 4910496., 4970730., 4970839., 4970870.,
       4970904., 4970953., 4970961., 4975358., 5010504., 5071217.,
       5073601., 5075556., 5075564., 5110512., 5171407., 5171423.,
       5171449., 5171464., 5210520., 5271639., 5375028., 5376513.,
       5471837., 5471860., 5476794., 5510553., 5572389., 5610561.,
       5672520., 5673874., 5676828., 5710579., 5772694., 5772702.,
       5772710., 5810587., 5872769.,      nan])

In [37]:
sat["CDCode"].astype(float).unique()

array([ 661598.,  661606., 1964733., 3073635., 3367215., 1363107.,
       3367033., 3667827., 1563776., 1964634., 3367181., 3675051.,
       3675077., 3768338., 1062117., 3367090., 3968676., 1975663.,
       1975713., 2966357., 3073650., 4168924.,  761796., 1263040.,
       1964246., 1964873., 3175085., 3768163., 4169047., 4169070.,
        161200., 1162646., 1910199., 3467314., 3868478.,  161259.,
       2165482., 3310330., 3467421., 3910397., 4269229.,  761721.,
       1075234., 1075275., 3076893., 3375176., 3667678.,  961853.,
       1964394., 2465755., 3667876., 3968585., 4710470., 1965060.,
       2465789., 3467447., 1262810., 2065201., 2065243., 3166894.,
       1964568., 1973437., 3066670., 3476505., 3675044., 3768346.,
       4970722., 4970730., 4776455., 5373833., 5471803.,  161119.,
       1563529., 1965128., 1965136., 3066647., 3667934., 4369427.,
       3976760., 5475325., 4870540., 5472249., 3710371., 3768411.,
       4068841., 4369534.,  161127., 1062414., 2910298., 5071134.,
       5672546., 5071175., 4469823.,  910090., 1964378., 3066514.,
       3066522., 3467439., 3768296., 4275010., 4276786., 5075739.,
       1563818., 1973445., 1975291., 1975309.,  161176., 1075127.,
       1875036., 3073924.,  761788., 1262687., 3066431., 3375242.,
       3667710., 1310132., 1964881., 3667843., 3768304., 1964865.,
       2165417., 3667777., 1010108., 1964451., 3367082., 3968593.,
        561556.,  661614., 2773825., 4068809., 2075606., 2076414.,
       3166928., 3667736., 3768106., 3768130., 4269112., 3066548.,
       3367058., 1965094., 2573593., 3968627., 4369401., 5472256.,
       3768213., 5772702., 5271571., 5376513.,  461432., 1062166.,
       3367124., 1563685., 4970870., 5575184., 3768452., 4970953.,
       1964725., 1964774., 1975333., 3375200., 3773791., 4369666.,
       5672652., 5071217., 1964337., 3366993., 5171464.,  110017.,
        461424.,  461440., 1964535., 2710272., 2765979.,  161242.,
       1363115., 2375218., 3467330.,  761648.,  761663., 1062547.,
       1764014., 1764022., 3375192., 3667686., 3768023.,  373981.,
        461408., 1563628., 2766092., 1964584., 3367207.,  561564.,
       1062265., 1964659., 1864139., 1976869.,  161192., 3776471.,
       3777099., 1964352., 2365565.,  161291., 1965029., 4310439.,
       1964279., 3667801., 3768189., 4169062., 4410447., 1663925.,
       2866241.,  175101., 3066621., 4670177.,  973783., 5410546.,
       4068759., 4369468., 5475523., 4970920., 4369674., 5071043.,
       4168890., 4970961., 4975358., 5673874., 5073601., 3968577.,
       4570136.,  761754., 5772678.,  761804., 2165466., 1964212.,
       3066449.,  161309., 2475317., 2475366., 2775473., 3767983.,
       3768403., 1964857., 3066464.,  761630., 1663891., 3667652.,
       1964527., 4870573.,  761697., 5010504.,  861820.,  961838.,
       4277198., 3066597., 4369583., 5672603., 3775416., 3775614.,
       5673759., 1864162., 1964790., 5673940., 1964980., 2365623.,
       4469799., 2173361., 5171415., 3367173.,  710074., 1062364.,
       1062380., 3367249., 3373676., 3667611.,  161275., 1964436.,
       1563412., 3166944., 1964907., 1663875., 1973460., 3575259.,
       3010306., 3773551., 4369641., 1363149., 1964303., 1073809.,
       3768049., 4975390., 3366977., 3467413., 5171373., 4770516.,
       4773684., 3473973., 5471860., 4970656., 4970839., 5572413.,
       5610561., 1964840., 4469807., 4570169., 1964519., 1210124.,
        161234., 3768122., 1062125., 2565896., 1073965., 3667850.,
       4269328.,  410041., 1410140., 2365540.,  761739., 1075408.,
       2010207., 3773569.,  661622., 1964683., 2866266., 5271506.,
       4870532., 3475283., 3667959., 5471993.,  461531., 2766159.,
       1573742., 1973452., 5071092., 5872769., 4569856., 1964329.,
       1563826., 3975499., 1062539., 1964261., 3768171., 1062331.,
       1663958., 3073643., 4369609., 1864204., 4973882., 5672520.,
       5471837., 4970607., 4068700., 4369484., 4970862., 3776901.,
       4475432., 5075556., 5772710., 1363214., 1463297., 1510157.,
       4277206., 4269310., 5872728., 3673890.,  961903., 2465730.,
       1673932., 1764030., 1975341.,  161168., 1764055., 3110314.,
        510058., 3266969., 3467322., 1563677., 1964287., 4269260.,
       5171407.,  161143., 1964709.,  810082., 1463271., 2365599.,
       1964311., 1964964., 1110116., 1162661., 1964592., 1573908.,
       3673957., 4569989., 5810587., 4870565., 4970706., 5572389.,
       1663982., 3667868., 3968502., 4277222., 5171456., 5075564.,
       2365615., 2766068., 1262901., 3410348., 1062158., 2673692.,
       1076778., 1176562., 2075580., 1964808., 4168999., 5271639.,
       4870581., 5475531., 5071167., 3768155., 5210520., 5872736.,
       1463248., 2365557., 3366985., 1073999., 1275515., 1964295.,
       1964469., 3777107., 4575267., 3968650., 3166951., 5310538.,
       4870524.,  461515., 1062257., 1563859., 4970904., 1975697.,
       3968569., 3066555., 2410249., 1776976., 2573585., 2673668.,
       3667892., 2365581.,  475507., 1575168., 3166845., 5071068.,
       1964576., 1275382., 4770466., 5472140., 5476836., 5676828.,
       5772686., 4269146., 1976885., 1976968., 1976992., 2976877.,
       3367157., 1964691., 3667637., 4075457., 5075572., 5375028.,
       2473619., 4970797., 3667587., 5672454., 1062430., 5171449.,
       5772694., 1363099., 1363164., 3777032., 1275374., 1476687.,
       2465698., 2775150., 3610363., 1964444.,  175093., 2610264.,
       2866290., 5476794., 1162653., 4168940., 4373387., 4469765.,
       5171423., 4510454., 3467355., 5171399.,  161150., 1363081.,
       2766134., 3675069., 3367116., 1075598., 4168916., 1175481.,
       3776851., 1263032., 1965052., 2765987., 1062281., 2775440.,
       3567538., 2265532., 1463289., 2365607., 4010405., 1864089.,
       3768031., 4770250., 4068833., 4075465., 5672470., 4277214.,
       4570110., 2373866., 2373916., 5075549.,  900000., 1900000.,
       2000000., 5700000., 1500000., 2800000., 4400000., 4600000.,
       3400000., 3600000.,  500000., 2200000., 3100000., 5500000.,
       2300000., 3000000., 4000000., 4100000., 2100000., 4700000.,
       1100000., 3900000., 5400000.,  100000., 1000000., 4900000.,
       5100000., 2700000., 5000000., 2900000., 4800000.,  200000.,
        300000., 2400000., 2600000., 3700000., 5200000., 5300000.,
        800000., 1800000., 3500000., 5800000., 1200000., 1300000.,
       4500000.,  400000.,  600000., 1400000., 2500000., 4200000.,
       4300000., 5600000., 1600000., 3200000., 3300000.,       0.,
       5110512., 5510553., 5710579., 4210421., 2110215., 4910496.,
       4810488.,  310033., 1610165., 2310231., 2810280., 3810389.,
       4110413.,  700000., 1700000., 3800000.,      nan])